language: go
go_import_path: github.com/ailabstw/go-pttai
sudo: false
matrix:
  include:
    # This builder only tests code linters on latest version of Go
    - os: linux
      dist: xenial
      go: 1.12.x
      env:
        - lint
      git:
        submodules: false # avoid cloning ethereum
      script:
        - go run build/ci.go lint

    # This builder only does unit-test on latest version of Go
    - os: linux
      dist: xenial
      go: 1.12.x
      env:
        - test
      git:
        submodules: false # avoid cloning ethereum
      script:
        - go run build/ci.go test
